apiVersion: v1
data:
  kubeadmin: JDJhJDEwJHMzR2NBc05iV2hyeWFBOHNwekRLaXVNRXF0LjZwTXRPLmc5U2Rmd2hUVC4xbXNrOEVaSGtX
kind: Secret
metadata:
  creationTimestamp: "2025-05-22T10:39:40Z"
  name: kubeadmin
  namespace: 
    kube-system
  resourceVersion: "368"
  uid: a8b48923-337a-4cf1-a842-c8b17c0360d5
type: Opaque
